//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatSUPDesktopApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reading, Problem-Solving games, choreography (like for ballet, Zumba), meditation" +
            "\r\n, creative writing, speaking a foreign language (actual motor movements of the" +
            " mouth)")]
        public string defaultHealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Substance use can negatively impact all of these tasks, making it harder to think" +
            ", make decisions, and set goals. Using substances may also cause slurred speech." +
            " ")]
        public string defaultUnhealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("helps to process memory(the hippocampus is located in this lobe) and hearing.")]
        public string defaultFunctionsTemporalLobe {
            get {
                return ((string)(this["defaultFunctionsTemporalLobe"]));
            }
            set {
                this["defaultFunctionsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any memory games (matching, Simon, etc), Distinguishing different instruments by " +
            "their sounds,\r\nDistinguishing different animals by their sounds, Recognizing pat" +
            "terns in music (auditory)\r\n")]
        public string defaultHealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" Substances, like marijuana and depressants, impair memory and learning. These su" +
            "bstances make it harder for the person to stay focused on tasks and remember inf" +
            "ormation.")]
        public string defaultUnhealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" helps humans process sensations (think the 5 senses), and understand where the b" +
            "ody is in space.")]
        public string defaultFunctionsParietalLobe {
            get {
                return ((string)(this["defaultFunctionsParietalLobe"]));
            }
            set {
                this["defaultFunctionsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Language comprehension (ie. learning definitions of words, engaging in face to fact conversation),
Body positioning & awareness (ie. yoga, aiming a pitch), Sensory perception (ie. reading braille, 
distinguishing coins by how the edges feel to the skin)
")]
        public string defaultHealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nLong term alcohol use has been shown to decrease gray matter in the parietal lo" +
            "be, which causes the person to have difficulty processing spatial relationships." +
            "")]
        public string defaultUnhealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("is responsible for visual processing")]
        public string defaultFunctionsOccipitalLobe {
            get {
                return ((string)(this["defaultFunctionsOccipitalLobe"]));
            }
            set {
                this["defaultFunctionsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual recognition (ie. identifying faces in a yearbook, \r\ndistinguishing differe" +
            "nt features in pictures, jigsaw puzzles, recognizing visual patterns)\r\n")]
        public string defaultHealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Long term alcohol use has been shown to decrease gray matter in the occipital lob" +
            "e, which would cause problems in visual processing and perception. \r\n")]
        public string defaultUnhealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("is responsible for balance, coordination, and posture. This brain part contains 8" +
            "0% of the brain’s neurons. The cerebellum also transmits signals to the rest of " +
            "the body. ")]
        public string defaultFunctionsCerebellum {
            get {
                return ((string)(this["defaultFunctionsCerebellum"]));
            }
            set {
                this["defaultFunctionsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any type of physical exercise, activities that help improve improve balance and c" +
            "oordination\r\nPairing physical exercise with a mental exercise (ie. dancing and s" +
            "inging simultaneously; \r\nstanding on a balance board while reciting the alphabet" +
            ")")]
        public string defaultHealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultHealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultHealthyBehaviorsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("People with substance use disorder showed more changes in the cerebellum than tho" +
            "se without substance use disorder. Addiction had a negative impact on the storag" +
            "e, processing, and regenerating capacity of the brain. \r\n")]
        public string defaultUnhealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultUnhealthyBehaviorsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("processes short term memory (STM), sometimes called “working memory”.")]
        public string defaultFunctionsHippocampus {
            get {
                return ((string)(this["defaultFunctionsHippocampus"]));
            }
            set {
                this["defaultFunctionsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Repeating a phone number to help you remember it\r\nMatching games, doing mental ma" +
            "th problems (without using paper)\r\n")]
        public string defaultHealthyBehaviorsHippocampus {
            get {
                return ((string)(this["defaultHealthyBehaviorsHippocampus"]));
            }
            set {
                this["defaultHealthyBehaviorsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"STM only holds about 7-9 digits and lasts 15-30 seconds before the information is either forgotten or sent to long term memory. Substance use impairs STM. For instance, someone who is intoxicated may not remember details of an event they would otherwise remember sober. ")]
        public string defaultUnhealthyBehaviorsHippocampus {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsHippocampus"]));
            }
            set {
                this["defaultUnhealthyBehaviorsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("triggers emotionally charged reactions, particularly survival instincts (fear & a" +
            "ggression), hypersensitive to stress, has a role in storing emotional memories, " +
            "in the Limbic System, and makes associations between the emotion and the environ" +
            "ment.")]
        public string defaultFunctionsAmygdala {
            get {
                return ((string)(this["defaultFunctionsAmygdala"]));
            }
            set {
                this["defaultFunctionsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Breathing exercises when you feel stressed, anxious or angry\r\nRecognizing when yo" +
            "u feel angry/stressed/fearful and being able to minimize those feelings-- thinki" +
            "ng logically\r\nAny healthy behaviors that will help you de-escalate stressful fee" +
            "lings\r\n")]
        public string defaultHealthyBehaviorsAmygdala {
            get {
                return ((string)(this["defaultHealthyBehaviorsAmygdala"]));
            }
            set {
                this["defaultHealthyBehaviorsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("After the high of an addictive substance, the neurotransmitter dopamine floods th" +
            "e brain, causing the amygdala creates an emotionally charged memory. This memory" +
            " increases the likelihood that the person will use the drug again. ")]
        public string defaultUnhealthyBehaviorsAmygdala {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsAmygdala"]));
            }
            set {
                this["defaultUnhealthyBehaviorsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("regulates growth hormones and hormones that stimulate the thyroid,Ttriggers onset" +
            " of puberty. Attached to the hypothalamus, in the Limbic System ")]
        public string defaultFunctionsPituitaryGland {
            get {
                return ((string)(this["defaultFunctionsPituitaryGland"]));
            }
            set {
                this["defaultFunctionsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Eating high protein foods (eggs, fish, poultry, etc)\r\nEating foods with vitamin A" +
            " & E\r\nGetting enough vitamin D (the best way is getting outside for sunshine!)\r\n" +
            "")]
        public string defaultHealthyBehaviorsPituitaryGland {
            get {
                return ((string)(this["defaultHealthyBehaviorsPituitaryGland"]));
            }
            set {
                this["defaultHealthyBehaviorsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Research has shown that THC, the chemical in marijuana that causes a high, suppre" +
            "sses hormone production in the pituitary. This hormone reduction particularly af" +
            "fects males and can lead to infertility later in life. \r\n")]
        public string defaultUnhealthyBehaviorsPituitaryGland {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsPituitaryGland"]));
            }
            set {
                this["defaultUnhealthyBehaviorsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"controls flow of messages between the brain and the rest of the body. Also controls basic body function like breathing, swallowing, heartbeat (medulla), sleep regulation (pons), etc. Serves as a connection between the central nervous system (cns) and the brain.")]
        public string defaultFunctionsBrainstem {
            get {
                return ((string)(this["defaultFunctionsBrainstem"]));
            }
            set {
                this["defaultFunctionsBrainstem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Good sleep routine (going to sleep the same time each night, avoiding screens hour before bed, getting adequate sleep, etc)
Impulse control (practicing small acts of self-control--  controlling the urge to punch someone :) or controlling road rage, or reaching for that extra cookie)
")]
        public string defaultHealthyBehaviorsBrainstem {
            get {
                return ((string)(this["defaultHealthyBehaviorsBrainstem"]));
            }
            set {
                this["defaultHealthyBehaviorsBrainstem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Substances, like depressants, slow down the communication between the cns and the brain. Also, the brainstem helps trigger the survival functions of the brain. As the body develops tolerance to the substance, the brain and body react as if the substance is needed for survival. (ie. if the body doesn’t get a drink, it will die.)
")]
        public string defaultUnhealthyBehaviorsBrainstem {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsBrainstem"]));
            }
            set {
                this["defaultUnhealthyBehaviorsBrainstem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"helps with planning, reasoning, voluntary movement (motor cortex is in the frontal lobe), problem solving, regulating emotions (the frontal lobe doesn’t initiate the emotion, but it helps us control our emotions), making judgements, planning for the future, and controlling the motor functions for speech.")]
        public string defaultFunctionsFrontalLobe {
            get {
                return ((string)(this["defaultFunctionsFrontalLobe"]));
            }
            set {
                this["defaultFunctionsFrontalLobe"] = value;
            }
        }
    }
}
