//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveBrain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("planning, reasoning, speech, voluntary movement (motor cortex is in the frontal l" +
            "obe), problem solving, regulating emotions (the frontal lobe doesn’t initiate th" +
            "e emotion, but it helps us control our emotions)\"")]
        public string defaultFunctionsFrontalLobe {
            get {
                return ((string)(this["defaultFunctionsFrontalLobe"]));
            }
            set {
                this["defaultFunctionsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reading, Problem-Solving games, choreography (like for ballet, Zumba), meditation" +
            "\r\n")]
        public string defaultHealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hearing, processing short term memory (hippocampus located in this lobe)")]
        public string defaultFunctionsTemporalLobe {
            get {
                return ((string)(this["defaultFunctionsTemporalLobe"]));
            }
            set {
                this["defaultFunctionsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sensory processing such as temperature, pressure, touch, & pain")]
        public string defaultFunctionsParietalLobe {
            get {
                return ((string)(this["defaultFunctionsParietalLobe"]));
            }
            set {
                this["defaultFunctionsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("visual Processing")]
        public string defaultFunctionsOccipitalLobe {
            get {
                return ((string)(this["defaultFunctionsOccipitalLobe"]));
            }
            set {
                this["defaultFunctionsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Balance & coordination")]
        public string defaultFunctionsCerebellum {
            get {
                return ((string)(this["defaultFunctionsCerebellum"]));
            }
            set {
                this["defaultFunctionsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any type of physical exercise, activities that help improve attention span")]
        public string defaultHealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultHealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultHealthyBehaviorsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultUnhealthyBehaviorsCerebellum"] = value;
            }
        }
    }
}
