//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveBrain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("planning, reasoning, speech, voluntary movement (motor cortex is in the frontal l" +
            "obe), problem solving, regulating emotions (the frontal lobe doesn’t initiate th" +
            "e emotion, but it helps us control our emotions)\"")]
        public string defaultFunctionsFrontalLobe {
            get {
                return ((string)(this["defaultFunctionsFrontalLobe"]));
            }
            set {
                this["defaultFunctionsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Reading, Problem-Solving games, choreography (like for ballet, Zumba), meditation" +
            "\r\n, creative writing, speaking a foreign language (actual motor movements of the" +
            " mouth)")]
        public string defaultHealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsFrontalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsFrontalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsFrontalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hearing, processing short term memory (hippocampus located in this lobe)")]
        public string defaultFunctionsTemporalLobe {
            get {
                return ((string)(this["defaultFunctionsTemporalLobe"]));
            }
            set {
                this["defaultFunctionsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any memory games (matching, Simon, etc), Distinguishing different instruments by " +
            "their sounds,\r\nDistinguishing different animals by their sounds, Recognizing pat" +
            "terns in music (auditory)\r\n")]
        public string defaultHealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsTemporalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsTemporalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsTemporalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sensory processing such as temperature, pressure, touch, & pain")]
        public string defaultFunctionsParietalLobe {
            get {
                return ((string)(this["defaultFunctionsParietalLobe"]));
            }
            set {
                this["defaultFunctionsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Language comprehension (ie. learning definitions of words, engaging in face to fact conversation),
Body positioning & awareness (ie. yoga, aiming a pitch), Sensory perception (ie. reading braille, 
distinguishing coins by how the edges feel to the skin)
")]
        public string defaultHealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsParietalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsParietalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsParietalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual Processing")]
        public string defaultFunctionsOccipitalLobe {
            get {
                return ((string)(this["defaultFunctionsOccipitalLobe"]));
            }
            set {
                this["defaultFunctionsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual recognition (ie. identifying faces in a yearbook, \r\ndistinguishing differe" +
            "nt features in pictures, jigsaw puzzles, recognizing visual patterns)\r\n")]
        public string defaultHealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultHealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultHealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsOccipitalLobe {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsOccipitalLobe"]));
            }
            set {
                this["defaultUnhealthyBehaviorsOccipitalLobe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Balance & coordination")]
        public string defaultFunctionsCerebellum {
            get {
                return ((string)(this["defaultFunctionsCerebellum"]));
            }
            set {
                this["defaultFunctionsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Any type of physical exercise, activities that help improve improve balance and c" +
            "oordination\r\nPairing physical exercise with a mental exercise (ie. dancing and s" +
            "inging simultaneously; \r\nstanding on a balance board while reciting the alphabet" +
            ")")]
        public string defaultHealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultHealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultHealthyBehaviorsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsCerebellum {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsCerebellum"]));
            }
            set {
                this["defaultUnhealthyBehaviorsCerebellum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("processes short-term memory to convert into long term memory, in limbic system (n" +
            "ote long term memories are stored all over the brain)")]
        public string defaultFunctionsHippocampus {
            get {
                return ((string)(this["defaultFunctionsHippocampus"]));
            }
            set {
                this["defaultFunctionsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsHippocampus {
            get {
                return ((string)(this["defaultHealthyBehaviorsHippocampus"]));
            }
            set {
                this["defaultHealthyBehaviorsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsHippocampus {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsHippocampus"]));
            }
            set {
                this["defaultUnhealthyBehaviorsHippocampus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("responsible for emotions, particularly survival instincts (fear & aggression), hy" +
            "persensitive to stress, role in storing emotional memories, in Limbic System")]
        public string defaultFunctionsAmygdala {
            get {
                return ((string)(this["defaultFunctionsAmygdala"]));
            }
            set {
                this["defaultFunctionsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsAmygdala {
            get {
                return ((string)(this["defaultHealthyBehaviorsAmygdala"]));
            }
            set {
                this["defaultHealthyBehaviorsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsAmygdala {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsAmygdala"]));
            }
            set {
                this["defaultUnhealthyBehaviorsAmygdala"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("regulates growth hormone, triggers onset of puberty. Attached to the hypothalamus" +
            ", in Limbic System")]
        public string defaultFunctionsPituitaryGland {
            get {
                return ((string)(this["defaultFunctionsPituitaryGland"]));
            }
            set {
                this["defaultFunctionsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsPituitaryGland {
            get {
                return ((string)(this["defaultHealthyBehaviorsPituitaryGland"]));
            }
            set {
                this["defaultHealthyBehaviorsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsPituitaryGland {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsPituitaryGland"]));
            }
            set {
                this["defaultUnhealthyBehaviorsPituitaryGland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("controls flow of messages between the brain and the rest of the body. Also contro" +
            "ls basic body function like breathing, swallowing, heartbeat (medulla), sleep re" +
            "gulation (pons), etc.")]
        public string defaultFunctionsBrainstem {
            get {
                return ((string)(this["defaultFunctionsBrainstem"]));
            }
            set {
                this["defaultFunctionsBrainstem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultHealthyBehaviorsBrainstem {
            get {
                return ((string)(this["defaultHealthyBehaviorsBrainstem"]));
            }
            set {
                this["defaultHealthyBehaviorsBrainstem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string defaultUnhealthyBehaviorsBrainstem {
            get {
                return ((string)(this["defaultUnhealthyBehaviorsBrainstem"]));
            }
            set {
                this["defaultUnhealthyBehaviorsBrainstem"] = value;
            }
        }
    }
}
